In [4]:
import PIL.Image as Image 
import PIL.ImageFilter as ImageFilter
import numpy as np
#Read image

im = Image.open( 'small_mario.jpg' )
#Display image
im=im.convert(mode="L")
im

In [5]:
#Applying a filter to the image
im_blur = im.filter(ImageFilter.GaussianBlur(1))
im_blur

In [6]:
pixels=list(im.getdata())
width, height =im.size
pixels = np.array([pixels[i * width:(i + 1) * width] for i in range(height)])
print(pixels)

[[  5   4  53  55  89  72 104  48   3]
 [  5   1  50  66  69  72  37  38  33]
 [  5  33  42  82 179  87  86  70  86]
 [  4  75 152  34 197 103 156 171  18]
 [  2  92  18 156 197 105  78  99  52]
 [ 56  92  75  84  73  85  48  50  37]
 [115 227  97  39  86  67  56  69  88]
 [ 21 128  43  54 115  82  60 124  66]
 [ 12 112  88  41  76  43 149 109  18]
 [ 10  56  70  15   6  58  57  86   6]]


Original Image Matrix

In [7]:
pixels2=list(im_blur.getdata())
width, height =im.size
pixels2 = np.array([pixels2[i * width:(i + 1) * width] for i in range(height)])
print(pixels2)

[[  8  19  42  62  74  76  68  49  29]
 [ 11  24  47  70  85  82  70  56  43]
 [ 18  38  62  87 108 102  90  77  63]
 [ 29  54  79 103 124 118 106  91  68]
 [ 45  66  83 104 120 109  94  81  63]
 [ 74  88  87  91  96  87  74  67  61]
 [ 92 105  90  78  79  76  71  71  69]
 [ 72  89  80  69  73  76  80  80  70]
 [ 47  68  68  57  59  70  82  78  55]
 [ 34  54  56  43  42  58  72  67  41]]


Blurred Image Matrix

In [8]:
diff_pixel=pixels2-pixels
print (diff_pixel)

[[   3   15  -11    7  -15    4  -36    1   26]
 [   6   23   -3    4   16   10   33   18   10]
 [  13    5   20    5  -71   15    4    7  -23]
 [  25  -21  -73   69  -73   15  -50  -80   50]
 [  43  -26   65  -52  -77    4   16  -18   11]
 [  18   -4   12    7   23    2   26   17   24]
 [ -23 -122   -7   39   -7    9   15    2  -19]
 [  51  -39   37   15  -42   -6   20  -44    4]
 [  35  -44  -20   16  -17   27  -67  -31   37]
 [  24   -2  -14   28   36    0   15  -19   35]]
